### ISSUE TITLE
Deprecated constructor names

### ISSUE THREAD

**Issue by giespaepen** [BorisMorel/IcalBundle#16]
After installing the bundle I have the following warning:

`PHP Deprecated:  Methods with the same name as their class will not be constructors in a future version of PHP; vcalendar has a deprecated constructor in .../vendor/bomo/ical-bundle/BOMO/IcalBundle/lib/kigkonsult/icalcreator/iCalcreator.class.php on line 57`

**Comment by BorisMorel** [comment]
Hi,

Please refere to #15.
