### ISSUE TITLE
Dev-master should not be required

### ISSUE THREAD

**Issue by nataliaAznar** [BorisMorel/IcalBundle#21]
In the composer.json, a "dev-master" branch from a project is required. This is not stable, and composers default configuration does not allow it:

Problem 1
    - bomo/ical-bundle v1.0.6 requires kigkonsult/icalcreator dev-master -> satisfiable by kigkonsult/icalcreator[dev-master] but these conflict with your requirements or minimum-stability.

**Comment by BorisMorel** [comment]
Solved by #24

**Comment by BorisMorel** [comment]
With the previous merge #19 README lost informations about this.
