### ISSUE TITLE
Symfony 4 support

### ISSUE THREAD

**Issue by atillay** [BorisMorel/IcalBundle#33]
I'm not able to use the bundle on Symfony 4 project because of this requirement : 
https://github.com/BorisMorel/IcalBundle/blob/1eb055fff75e164c0ae7d891ef097fb22b7014dd/composer.json#L23

Is there any reason why it should not allow framework bundle v4 ?

**Comment by BorisMorel** [comment]
Because I didn't test this code on SF4.
But If it's works can you make a PR on a non master branch that I can merge.

Thanks,

**Comment by BorisMorel** [comment]
OK. So I need to test this.

**Comment by MrMitch** [comment]
#37 add Symfony 4 compatibility

**Comment by BorisMorel** [comment]
PR was merged. Now Symfony 4 is supported.
Thanks MrMitch
